log:
  export_gantt: false
  gantt_directory: ./gantt
  output_directory: ../data/
  print_log: true
model:
  model_name: deepseekV3
serving:
  max_batch_size: 32
  max_process_token: 0
simulation:
  data: synthesis
  exit_out_of_memory: false
  injection_rate: 20
  input_len: 1024
  iter: 500
  latency_margin: 1.0
  mem_cap_limit: false
  optimizer_latency_model: max
  output_len: 256
  precision_byte: 0
  skewness: 0.8
  validate_optimizer: warn
  validate_optimizer_threshold: 0.1
system:
  chunk_size: 0
  distribution:
    expert_tensor_degree: 1
    none_expert_tensor_degree: 8
    pipeline_degree: 1
  gpu_gen: Rubin
  infiniband_gen: 800
  memory_type: HBM
  num_device: 8
  num_node: 1
  nvlink_gen: 6
  optimization:
    compressed_kv: true
    decode_mode: true
    disagg_system: false
    hetero_subbatch: false
    kv_cache_reuse_rate: 0.2
    parallel_execution: false
    prefill_mode: false
    reuse_kv_cache: true
    use_absorb: true
    use_flash_attention: true
    use_flash_mla: true
    use_low_unit_moe_only: false
    use_ramulator: false
  optimize_parallelism: false
  processor_type: GPU
  tpot_slo: 0.1
